# Generated by Django 6.1 on 2026-08-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
